### ISSUE TITLE
Pokemon cards

### ISSUE THREAD

**Issue by teifler** [FaGru/pokeapp#1]
## Value proposition
**As a** User
**I need** a list of pokemon
**to be able to** see information about them

## Acceptance Criteria
- [ ] There is a list of pokemon with informations
## Tasks
- [ ] Add GlobalStyles with main colors
- [ ] Create -> components/PokeCard
- [ ] Add tests
- [ ] Check accessibility with lighthouse
