### ISSUE TITLE
State management (Zustand)

### ISSUE THREAD

**Issue by teifler** [FaGru/pokeapp#13]
## Value proposition

**As a** developer
**I need** statemanagment
**to be able to** write clean code and to keep components dumb

## Acceptance Criteria
Add a state management system

- [x] Add Zustand to App
- [x] Create useStore

## Tasks

- [x] Add Zustand to App
- [x] Add useStore
- [x] Change states from useState to useStore
- [x] Update tests
- [x] Check app
