### ISSUE TITLE
stats & evolution component

### ISSUE THREAD

**Issue by FaGru** [FaGru/pokeapp#15]
## Value proposition

**As a** User
**I need** a stats & evolution component
**to get** more informations about each pokemon 

## Acceptance Criteria

- [ ] stats component is visible after clickin on the stats button
- [ ] evolution component is visible after clickin on the evolution button

## Tasks

- [ ] create -> comontents/detailStats
     - [ ] Add test 
- [ ] create -> comontents/detailEvolution
     - [ ] Add test
- [ ] check on mobile device
- [ ] check accessibility
