### ISSUE TITLE
DetailPage header and about

### ISSUE THREAD

**Issue by FaGru** [FaGru/pokeapp#7]
## Value proposition

**As a** User 
**I need a** structured DetailPage
**to get** better Informations about each Pokemon

## Acceptance Criteria

- [ ] There are more Informations on each Pokemon

## Tasks

- [ ] Create -> components/DetailHeader
- [ ] Create -> components/DetailAbout
- [ ] Check accessibility
- [ ] Add tests
