### ISSUE TITLE
Add Husky

### ISSUE THREAD

**Issue by teifler** [FaGru/pokeapp#9]
## Value proposition

**As a** Developer
**I need** to automate my tests
**to be able to**have a good experience

## Acceptance Criteria

- [x] Configure Husky for eslint
- [x] Add husky for github actions to automate tests

## Tasks

- [x]  Add .husky folder
- [x] Configure husky
